### ISSUE TITLE
Allow simpler config for license checks

### ISSUE THREAD

**Issue by luser** [EmbarkStudios/cargo-deny#116]
AFAICT currently [the `licenses` check](https://embarkstudios.github.io/cargo-deny/checks/licenses/index.html#evaluation-precedence) requires explicitly listing out allowed licenses since step 5 states that crates that don't match any other rules are implicitly rejected.

For our usage I would ideally like to be able to specify a list of denied licenses without having to spell out all of the allowed licenses. My initial thought was to simply use something like:
```toml
[licenses]
unlicensed = "deny"
copyleft = "deny"
```

This causes the license check to fail since I don't have an `allow` list. Perhaps being able to change the default behavior for step 5 would be the simplest fix? Something like:
```toml
[licenses]
unlicensed = "deny"
copyleft = "deny"
default = "allow"
```

If this is not something you'd consider, perhaps a "generate a valid configuration that allows all of the licenses for crates currently in use" command would be helpful.
