### ISSUE TITLE
Fails to find license information for ignored license

### ISSUE THREAD

**Issue by Phrohdoh** [EmbarkStudios/cargo-deny#16]
## Describe the bug
Before ignoring (via `deny.toml`) `*ring*`'s `LICENSE`, when running `cargo deny check` I see the following.

```
Aug 18 07:15:42.345 ERRO unable to determine license with high confidence, src: text=/Users/taryn/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.14.6/LICENSE,hash=0xbd0eed23, score: 0.6644706, crate: ring@0.14.6
```

I then add the following to my `deny.toml`.

```toml
[[licenses.ignore]]
name = "ring"
license_files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]
```

Upon running `cargo deny check` _again_ I see the following.

```
Aug 18 07:17:22.179 ERRO could not find any license information, crate: ring@0.14.6
```

## To Reproduce
- have `*ring*` as a dependency (direct or transitive)
- perform the above-noted steps

## Expected Behavior
I expect `*ring*` to be successfully ignored.

## Additional Information

I am using `cargo-deny` version `0.2.6`.
