### ISSUE TITLE
Support adding rules for specific folders

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/cargo-deny#20]
## Intro

For our larger Rust monorepo at Embark we have a base `deny.toml` to disallow certain crates and whitelist licenses for the entire workspace. This works well but we do also have certain more specific projects in subfolders that have additional constraints and that we want to limit more or differently so we want to add support for having specific rules, such as the ban/deny crate list that acts on a specific sub-folder but not the entire workspace.

For example: not allowing `rayon` crate to be used in our `modules/` folder because our crates there are dynamic libraries and either do not support internal parallelism or we don't want them to spawn up their own threadpools.

## Potential implementation

Right now I think we are primarily interested in just adding additional bans/deny rules for these folders. Could see a couple of different ways of defining it:

### Option 1 - in the main `deny.toml`

Directly in the current file by specifying paths:

```toml
[bans]
multiple_versions = "deny"
deny = [
    { name = "openssl" },
    
    # do not allow rayon to be used in our modules
    { name = "rayon", path = "modules/" }
]
```

### Option 2 - in its own subfolder `deny.toml`

Could add additional `deny.toml` files in the subfolders in question that just add the additional rules:

`modules/deny.toml`
```toml
[bans]
deny = [
    # do not allow rayon to be used in our modules
    { name = "rayon", path = "modules/" }
]
```

Do think I prefer _Option 1_ for the simplicity of having everything in the same place, but either would work and is related to how we want to evolve the format going forward (#17).

Would be some work to figure out a way to handle and find which dependencies are used by which crates in which folders also for this, that information, that information is not in `Cargo.lock`
