### ISSUE TITLE
Optional dependencies are not checked in vuln checks

### ISSUE THREAD

**Issue by roblabla** [EmbarkStudios/cargo-deny#313]
**Describe the bug**
When checking for vulnerabilities or yanked crates, optional dependencies are not checked.

While the current behavior might be reasonable to some use-case, we have some crates in which we gate various crates behind a bunch of optional features. This means `cargo deny` only ends up checking a subset of our tree. Having a `--all-features` flag/config option would allow us to properly check the whole tree for vulnerabilities across all our build configurations.

**To Reproduce**

```toml
[package]
name = "python-stuff"
version = "0.1.0"
authors = ["me"]
edition = "2018"
publish = false

[dependencies]
pyo3 = { version = "0.12.3", optional = true }
```

Lockfile (forces use of yanked version of pyo3):

```toml
[[package]]
name = "pyo3"
version = "0.12.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "a9b90d637542bbf29b140fdd38fa308424073fd2cdf641a5680aed8020145e3c"
dependencies = [
 "ctor",
 "indoc",
 "inventory",
 "libc",
 "parking_lot",
 "paste",
 "pyo3cls",
 "unindent",
]
```

deny.toml:

```toml
[advisories]
yanked = "deny"
```

Running `cargo deny check advisories` will print `advisories ok`, despite an optional dependency being yanked (and having a RUSTSEC advisory opened).

**Expected behavior**

I expect either cargo-deny to run on optional feature, or to provide a flag/config option to let the user chose to either test the default config or all features.

**Device:**
 - OS: linux
 - Version: `cargo-deny 0.8.1`
