### ISSUE TITLE
`allow` list dependencies only for wrapper crates

### ISSUE THREAD

**Issue by Evrey** [EmbarkStudios/cargo-deny#321]
**Is your feature request related to a problem? Please describe.**
I'm using an explicit `allow` list for dependencies, so that dependency updates don't unexpectedly pull more crates in. However, when using `allow`, any entries in `deny` with `wrappers = […]` are ignored.

The only work-around is for me to *also* `allow` these deps, but then every other crate may pull them in as well, which I do not want to happen.

**Describe the solution you'd like**
Add the `wrappers = […]` property to `allow`, which only allows a crate in the dependency, if any of the explicitly listed `wrappers` pulls it in.

**Describe alternatives you've considered**
Add a feature to ignore all `dev-dependencies`, despite having an `allow` list.

Perhaps another and more flexible solution would be the addition of `allow-release`, `allow-debug`, `allow-test`, `allow-bench` lists. If I then made my current `allow` list an `allow-release` and `allow-debug` list instead, then any `test` or `bench` dependencies are treated as if no explicit `allow` list existed.

Yet another solution would be to add a crate property for both, `allow` and `deny` lists that specifies for which profiles this crate rule is valid. So if I was to `allow = [{ name = "proptest", profiles = ["test"] }]`, then `proptest` must not appear outside of `dev-dependencies`.

The ideal solution, in my opinion, would be to have both, `wrappers = […]` in `allow` lists, *and* `profiles = […]` in any list. Note that `honggfuzz` tests are not `dev-dependencies`, but their own crates within a workspace with a bunch of binaries running in normal debug builds. Hence why I'd prefer having both attributes.

(**E:** Oh yeah, build deps exist, too.)

**Additional context**
While the »main code« of my projects uses very few cherry-picked dependencies, I also rely on a bunch of testing crates, mainly `honggfuzz` and `proptest`. While especially `proptest` pulls in a lot of junk I don't use, none of it is included in user-facing release or debug builds. And so I want there to be an easy way to express this »I don't care for dev deps« scenario.

Maybe this feature already exists, but I was not able to figure it out given the docs, in which case I instead propose improving them.

**Comment by Jake-Shadle** [comment]
It would be slightly easier to reason about your project setup if you could provide a link to the repo you are describing.

**Comment by Evrey** [comment]
That's actually quite tricky for closed-source software. But I can give you snippets of what the project structure roughly looks like.

Top level `Cargo.toml` has:
```toml
[workspace]
members = ["fuzzing", … other project crates…]
```
Next to it lay the `deny.toml`.

The `fuzzing` crate is full of:
```toml
[[bin]]
name = "some_test_case"
```
These are compiled and ran in debug mode by the `cargo hfuzz` tool. So its dependencies are not `dev-dependencies`.

The other project crates all have this:
```toml
[dev-dependencies.proptest]
version = …
```

The `deny.toml` has:
```toml
[bans]
multiple-versions = "deny"
highlight         = "all"
allow = [
  # a bunch of things for the project crates…

  # The two deps explicitly added for testing only
  {name = "honggfuzz"},
  {name = "proptest"},

  # a very long list of dependencies of `honggfuzz` and `proptest`, e.g. this
  {name = "lazy_static"},
]
deny = [
  # the docs read like this should work, if i remove it from `allow`
  # but it's just ignored instead and `cargo deny` complains about
  # `lazy_static` being implicitly blacklisted, because the `allow`
  # list exists.
  {name = "lazy_static", wrappers = ["proptest"]},
]
```
It all looks like this:
```
<project>
 |
 +--> fuzzing/
 |     |
 |     +--> src/test_group/
 |     |    |
 |     |    +--> test_case.rs
 |     |
 |     +--> Cargo.toml
 |
 +--> other_project_crates/
 |
 +--> Cargo.toml
 |
 +--> deny.toml
 |
 …
```
So what I wish for is a way for `cargo deny` to at least treat my dependency graph as if unit and fuzz testing did not exist.
