### ISSUE TITLE
Failed to fetch advisory database: git operation failed

### ISSUE THREAD

**Issue by hanabi1224** [EmbarkStudios/cargo-deny#388]
**Describe the bug**
cargo works with the combination of below ~/.gitconfig and ~/.cargo/config , but `cargo deny check advisories` fails with errors.

~/.gitconfig
```toml
[url "git@github.com:"]
        insteadOf = https://github.com/
```

~/.cargo/config
```toml
[net]
git-fetch-with-cli = true
```

Error:
```
2022-01-19 04:07:41 [ERROR] failed to fetch advisory database: git operation failed: failed to authenticate when downloading repository
attempted ssh-agent authentication, but none of the usernames `git` succeeded
```

**To Reproduce**
1. create ~/.gitconfig and ~/.cargo/config with the content above
2. run setup ssh keys for git cli
3. run `cargo update` against any crate, it should work fine
4. run `cargo deny check advisories`, it fails with error above

**Expected behavior**

**Screenshots**

**Device:**
 - OS: windows 11 / wsl2 Ubuntu 20.04

**Additional context**
