### ISSUE TITLE
`licenses.exceptions` doesn’t work with `licenses.clarify`

### ISSUE THREAD

**Issue by Jayman2000** [EmbarkStudios/cargo-deny#406]
**Describe the bug**
If you specify a crate’s license with `licenses.clarify` and allow that license using `licenses.exceptions`, then `cargo deny check license` will fail. Here’s a `deny.toml` that causes the error:

```toml
[licenses]
default = "deny"
allow-osi-fsf-free = "either"
deny = [
    "OpenSSL",
]

exceptions = [
    { allow = ["ISC", "MIT", "OpenSSL"], name = "ring" }
]

[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
```

**To Reproduce**
1. Download this [minimum reproduction project](https://github.com/EmbarkStudios/cargo-deny/files/8053587/cargo-deny-bug.zip).
2. Extract it and `cd` to its directory.
3. Run `cargo deny check license`.

**Expected behavior**
I expected no warnings or errors.

**Device:**
 - OS: Arch Linux
 - Browser: N/A
 - Version: 0.11.2 (0.11.1 doesn’t have this bug)
