### ISSUE TITLE
`git-fetch-with-cli = true` adds git output prior JSON with `cargo deny --format json check`

### ISSUE THREAD

**Issue by lcmgh** [EmbarkStudios/cargo-deny#438]
cargo-deny v0.12.1

When adding `git-fetch-with-cli = true` to `deny.toml` the output is not valid JSON anymore because output of the clone command is added.

`cargo deny --format json check 2> deny.json`

First 5 lines of `deny.json`:
```
Cloning into '/Users/user/.cargo/advisory-db/github.com-2f857891b7f43c59'...
{"fields":{"code":"B004","graphs":[{"name":"darling","parents":[{"name":"serde_with_macros","parents":[{"name":"serde_with","parents":[{"name":"bollard-stubs","parents":[{"name":"testcontainers","parents":[{"kind":"dev","name":"amusage-mileage-consumer","version":"0.1.3"},{"name":"amusage-mileage-consumer","repeat":true,"version":"0.1.3"}],"version":"0.14.0"}],"version":"1.41.0"}],"version":"1.14.0"}],"version":"1.5.2"}],"version":"0.13.4"},{"name":"darling","parents":[{"name":"derive_builder_core","parents":[{"name":"derive_builder_macro","parents":[{"name":"derive_builder","parents":[{"name":"kinesis-client","parents":[{"name":"amusage-mileage-consumer","version":"0.1.3"}],"version":"0.1.0"}],"version":"0.11.2"}],"version":"0.11.2"}],"version":"0.11.2"},{"name":"serde_with_macros","parents":[{"name":"serde_with","parents":[{"name":"kinesis-client","repeat":true,"version":"0.1.0"}],"version":"2.0.0"}],"version":"2.0.0"}],"version":"0.14.1"}],"labels":[{"column":1,"line":78,"message":"lock entries","span":"darling 0.13.4 registry+https://github.com/rust-lang/crates.io-index\ndarling 0.14.1 registry+https://github.com/rust-lang/crates.io-index"}],"message":"found 2 duplicate entries for crate 'darling'","severity":"warning"},"type":"diagnostic"}
{"fields":{"code":"B004","graphs":[{"name":"darling_core","parents":[{"name":"darling","parents":[{"name":"serde_with_macros","parents":[{"name":"serde_with","parents":[{"name":"bollard-stubs","parents":[{"name":"testcontainers","parents":[{"kind":"dev","name":"amusage-mileage-consumer","version":"0.1.3"},{"name":"amusage-mileage-consumer","repeat":true,"version":"0.1.3"}],"version":"0.14.0"}],"version":"1.41.0"}],"version":"1.14.0"}],"version":"1.5.2"}],"version":"0.13.4"},{"name":"darling_macro","parents":[{"name":"darling","repeat":true,"version":"0.13.4"}],"version":"0.13.4"}],"version":"0.13.4"},{"name":"darling_core","parents":[{"name":"darling","parents":[{"name":"derive_builder_core","parents":[{"name":"derive_builder_macro","parents":[{"name":"derive_builder","parents":[{"name":"kinesis-client","parents":[{"name":"amusage-mileage-consumer","version":"0.1.3"}],"version":"0.1.0"}],"version":"0.11.2"}],"version":"0.11.2"}],"version":"0.11.2"},{"name":"serde_with_macros","parents":[{"name":"serde_with","parents":[{"name":"kinesis-client","repeat":true,"version":"0.1.0"}],"version":"2.0.0"}],"version":"2.0.0"}],"version":"0.14.1"},{"name":"darling_macro","parents":[{"name":"darling","repeat":true,"version":"0.14.1"}],"version":"0.14.1"}],"version":"0.14.1"}],"labels":[{"column":1,"line":80,"message":"lock entries","span":"darling_core 0.13.4 registry+https://github.com/rust-lang/crates.io-index\ndarling_core 0.14.1 registry+https://github.com/rust-lang/crates.io-index"}],"message":"found 2 duplicate entries for crate 'darling_core'","severity":"warning"},"type":"diagnostic"}
{"fields":{"code":"B004","graphs":[{"name":"darling_macro","parents":[{"name":"darling","parents":[{"name":"serde_with_macros","parents":[{"name":"serde_with","parents":[{"name":"bollard-stubs","parents":[{"name":"testcontainers","parents":[{"kind":"dev","name":"amusage-mileage-consumer","version":"0.1.3"},{"name":"amusage-mileage-consumer","repeat":true,"version":"0.1.3"}],"version":"0.14.0"}],"version":"1.41.0"}],"version":"1.14.0"}],"version":"1.5.2"}],"version":"0.13.4"}],"version":"0.13.4"},{"name":"darling_macro","parents":[{"name":"darling","parents":[{"name":"derive_builder_core","parents":[{"name":"derive_builder_macro","parents":[{"name":"derive_builder","parents":[{"name":"kinesis-client","parents":[{"name":"amusage-mileage-consumer","version":"0.1.3"}],"version":"0.1.0"}],"version":"0.11.2"}],"version":"0.11.2"}],"version":"0.11.2"},{"name":"serde_with_macros","parents":[{"name":"serde_with","parents":[{"name":"kinesis-client","repeat":true,"version":"0.1.0"}],"version":"2.0.0"}],"version":"2.0.0"}],"version":"0.14.1"}],"version":"0.14.1"}],"labels":[{"column":1,"line":82,"message":"lock entries","span":"darling_macro 0.13.4 registry+https://github.com/rust-lang/crates.io-index\ndarling_macro 0.14.1 registry+https://github.com/rust-lang/crates.io-index"}],"message":"found 2 duplicate entries for crate 'darling_macro'","severity":"warning"},"type":"diagnostic"}
{"fields":{"code":"B004","graphs":[{"name":"hashbrown","parents":[{"name":"metrics-util","parents":[{"name":"metrics-exporter-prometheus","parents":[{"name":"amusage-mileage-consumer","version":"0.1.3"}],"version":"0.10.0"}],"version":"0.13.0"}],"version":"0.11.2"},{"name":"hashbrown","parents":[{"name":"hashlink","parents":[{"name":"sqlx-core","parents":[{"name":"sqlx","parents":[{"kind":"dev","name":"amusage-mileage-consumer","version":"0.1.3"},{"name":"amusage-mileage-consumer","repeat":true,"version":"0.1.3"}],"version":"0.6.0"},{"name":"sqlx-macros","parents":[{"name":"sqlx","repeat":true,"version":"0.6.0"}],"version":"0.6.0"}],"version":"0.6.0"}],"version":"0.8.0"},{"name":"indexmap","parents":[{"name":"h2","parents":[{"name":"hyper","parents":[{"name":"amusage-mileage-consumer","repeat":true,"version":"0.1.3"},{"name":"aws-config","parents":[{"name":"amusage-mileage-consumer","repeat":true,"version":"0.1.3"},{"name":"kinesis-client","parents":[{"name":"amusage-mileage-consumer","repeat":true,"version":"0.1.3"}],"version":"0.1.0"}],"version":"0.12.0"},{"name":"aws-smithy-client","parents":[{"name":"amusage-mileage-consumer","repeat":true,"version":"0.1.3"},{"name":"aws-config","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-dynamodb","parents":[{"name":"amusage-mileage-consumer","repeat":true,"version":"0.1.3"},{"name":"dynomutex","parents":[{"name":"kinesis-client","repeat":true,"version":"0.1.0"}],"version":"0.1.6"},{"name":"kinesis-client","repeat":true,"version":"0.1.0"},{"name":"serde_dynamo","parents":[{"name":"dynomutex","repeat":true,"version":"0.1.6"},{"name":"kinesis-client","repeat":true,"version":"0.1.0"}],"version":"4.0.4"}],"version":"0.12.0"},{"name":"aws-sdk-kinesis","parents":[{"name":"amusage-mileage-consumer","repeat":true,"version":"0.1.3"},{"name":"kinesis-client","repeat":true,"version":"0.1.0"}],"version":"0.12.0"},{"name":"aws-sdk-sso","parents":[{"name":"aws-config","repeat":true,"version":"0.12.0"}],"version":"0.12.0"},{"name":"aws-sdk-sts","parents":[{"name":"aws-config","repeat":true,"version":"0.12.0"}],"version":"0.12.0"},{"name":"aws-types","parents":[{"name":"amusage-mileage-consumer","repeat":true,"version":"0.1.3"},{"name":"aws-config","repeat":true,"version":"0.12.0"},{"name":"aws-endpoint","parents":[{"name":"aws-sdk-dynamodb","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-kinesis","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-sso","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-sts","repeat":true,"version":"0.12.0"}],"version":"0.12.0"},{"name":"aws-http","parents":[{"name":"aws-config","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-dynamodb","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-kinesis","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-sso","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-sts","repeat":true,"version":"0.12.0"}],"version":"0.12.0"},{"name":"aws-sdk-dynamodb","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-kinesis","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-sso","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-sts","repeat":true,"version":"0.12.0"},{"name":"aws-sig-auth","parents":[{"name":"aws-sdk-dynamodb","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-kinesis","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-sso","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-sts","repeat":true,"version":"0.12.0"}],"version":"0.12.0"},{"name":"kinesis-client","repeat":true,"version":"0.1.0"}],"version":"0.12.0"},{"name":"kinesis-client","repeat":true,"version":"0.1.0"}],"version":"0.42.0"},{"name":"aws-smithy-http","parents":[{"name":"aws-config","repeat":true,"version":"0.12.0"},{"name":"aws-endpoint","repeat":true,"version":"0.12.0"},{"name":"aws-http","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-dynamodb","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-kinesis","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-sso","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-sts","repeat":true,"version":"0.12.0"},{"name":"aws-sig-auth","repeat":true,"version":"0.12.0"},{"name":"aws-sigv4","parents":[{"name":"aws-sig-auth","repeat":true,"version":"0.12.0"}],"version":"0.12.0"},{"name":"aws-smithy-client","repeat":true,"version":"0.42.0"},{"name":"aws-smithy-http-tower","parents":[{"name":"aws-config","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-dynamodb","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-kinesis","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-sso","repeat":true,"version":"0.12.0"},{"name":"aws-sdk-sts","repeat":true,"version":"0.12.0"},{"name":"aws-smithy-client","repeat":true,"version":"0.42.0"}],"version":"0.42.0"},{"name":"aws-types","repeat":true,"version":"0.12.0"}],"version":"0.42.0"},{"name":"hyper-proxy","parents":[{"name":"kinesis-client","repeat":true,"version":"0.1.0"}],"version":"0.9.1"},{"name":"hyper-tls","parents":[{"name":"aws-smithy-client","repeat":true,"version":"0.42.0"},{"name":"hyper-proxy","repeat":true,"version":"0.9.1"},{"name":"reqwest","parents":[{"kind":"dev","name":"amusage-mileage-consumer","repeat":true,"version":"0.1.3"}],"version":"0.11.11"}],"version":"0.5.0"},{"name":"kinesis-client","repeat":true,"version":"0.1.0"},{"name":"metrics-exporter-prometheus","parents":[{"name":"amusage-mileage-consumer","repeat":true,"version":"0.1.3"}],"version":"0.10.0"},{"name":"reqwest","repeat":true,"version":"0.11.11"}],"version":"0.14.20"},{"name":"reqwest","repeat":true,"version":"0.11.11"}],"version":"0.3.13"},{"name":"metrics-exporter-prometheus","repeat":true,"version":"0.10.0"},{"name":"petgraph","parents":[{"name":"prost-build","parents":[{"kind":"build","name":"kinesis-client","repeat":true,"version":"0.1.0"}],"version":"0.10.4"}],"version":"0.6.2"},{"name":"serde_with","parents":[{"name":"kinesis-client","repeat":true,"version":"0.1.0"}],"version":"2.0.0"},{"name":"sqlx-core","repeat":true,"version":"0.6.0"}],"version":"1.9.1"}],"version":"0.12.3"}],"labels":[{"column":1,"line":119,"message":"lock entries","span":"hashbrown 0.11.2 registry+https://github.com/rust-lang/crates.io-index\nhashbrown 0.12.3 registry+https://github.com/rust-lang/crates.io-index"}],"message":"found 2 duplicate entries for crate 'hashbrown'","severity":"warning"},"type":"diagnostic"}
```

deny.toml
```toml
# This template contains all of the possible sections and their default values

# Note that all fields that take a lint level have these possible values:
# * deny - An error will be produced and the check will fail
# * warn - A warning will be produced, but the check will not fail
# * allow - No warning or error will be produced, though in some cases a note
# will be

# The values provided in this template are the default values that will be used
# when any section or field is not specified in your own configuration

# If 1 or more target triples (and optionally, target_features) are specified,
# only the specified targets will be checked when running `cargo deny check`.
# This means, if a particular package is only ever used as a target specific
# dependency, such as, for example, the `nix` crate only being used via the
# `target_family = "unix"` configuration, that only having windows targets in
# this list would mean the nix crate, as well as any of its exclusive
# dependencies not shared by any other crates, would be ignored, as the target
# list here is effectively saying which targets you are building for.
targets = [
    # The triple can be any string, but only the target triples built in to
    # rustc (as of 1.40) can be checked against actual config expressions
    #{ triple = "x86_64-unknown-linux-musl" },
    # You can also specify which target_features you promise are enabled for a
    # particular target. target_features are currently not validated against
    # the actual valid features supported by the target architecture.
    #{ triple = "wasm32-unknown-unknown", features = ["atomics"] },
]

# This section is considered when running `cargo deny check advisories`
# More documentation for the advisories section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html
[advisories]
git-fetch-with-cli = true
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# The lint level for security vulnerabilities
vulnerability = "deny"
# The lint level for unmaintained crates
unmaintained = "warn"
# The lint level for crates that have been yanked from their source registry
yanked = "warn"
# The lint level for crates with security notices. Note that as of
# 2019-12-17 there are no security notice advisories in
# https://github.com/rustsec/advisory-db
notice = "warn"
# A list of advisory IDs to ignore. Note that ignored advisories will still
# output a note when they are encountered.
ignore = [
    #"RUSTSEC-0000-0000",
]
# Threshold for security vulnerabilities, any vulnerability with a CVSS score
# lower than the range specified will be ignored. Note that ignored advisories
# will still output a note when they are encountered.
# * None - CVSS Score 0.0
# * Low - CVSS Score 0.1 - 3.9
# * Medium - CVSS Score 4.0 - 6.9
# * High - CVSS Score 7.0 - 8.9
# * Critical - CVSS Score 9.0 - 10.0
#severity-threshold =

# If this is true, then cargo deny will use the git executable to fetch advisory database.
# If this is false, then it uses a built-in git library.
# Setting this to true can be helpful if you have special authentication requirements that cargo-deny does not support.
# See Git Authentication for more information about setting up git authentication.
#git-fetch-with-cli = true

# This section is considered when running `cargo deny check licenses`
# More documentation for the licenses section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
# The lint level for crates which do not have a detectable license
unlicensed = "deny"
# List of explicitly allowed licenses
# See https://spdx.org/licenses/ for list of possible licenses
# [possible values: any SPDX 3.11 short identifier (+ optional exception)].
allow = [
    "MIT",
    "Apache-2.0",
    #"Apache-2.0 WITH LLVM-exception",
]
# List of explicitly disallowed licenses
# See https://spdx.org/licenses/ for list of possible licenses
# [possible values: any SPDX 3.11 short identifier (+ optional exception)].
deny = [
    #"Nokia",
]
# Lint level for licenses considered copyleft
copyleft = "warn"
# Blanket approval or denial for OSI-approved or FSF Free/Libre licenses
# * both - The license will be approved if it is both OSI-approved *AND* FSF
# * either - The license will be approved if it is either OSI-approved *OR* FSF
# * osi-only - The license will be approved if is OSI-approved *AND NOT* FSF
# * fsf-only - The license will be approved if is FSF *AND NOT* OSI-approved
# * neither - This predicate is ignored and the default lint level is used
allow-osi-fsf-free = "neither"
# Lint level used when no other predicates are matched
# 1. License isn't in the allow or deny lists
# 2. License isn't copyleft
# 3. License isn't OSI/FSF, or allow-osi-fsf-free = "neither"
default = "deny"
# The confidence threshold for detecting a license from license text.
# The higher the value, the more closely the license text must be to the
# canonical license text of a valid SPDX license file.
# [possible values: any between 0.0 and 1.0].
confidence-threshold = 0.8
# Allow 1 or more licenses on a per-crate basis, so that particular licenses
# aren't accepted for every possible crate as with the normal allow list
exceptions = [
    # Each entry is the crate and version constraint, and its specific allow
    # list
    #{ allow = ["Zlib"], name = "adler32", version = "*" },
]

# Some crates don't have (easily) machine readable licensing information,
# adding a clarification entry for it allows you to manually specify the
# licensing information
#[[licenses.clarify]]
# The name of the crate the clarification applies to
#name = "ring"
# The optional version constraint for the crate
#version = "*"
# The SPDX expression for the license requirements of the crate
#expression = "MIT AND ISC AND OpenSSL"
# One or more files in the crate's source used as the "source of truth" for
# the license expression. If the contents match, the clarification will be used
# when running the license check, otherwise the clarification will be ignored
# and the crate will be checked normally, which may produce warnings or errors
# depending on the rest of your configuration
#license-files = [
    # Each entry is a crate relative path, and the (opaque) hash of its contents
    #{ path = "LICENSE", hash = 0xbd0eed23 }
#]

[licenses.private]
# If true, ignores workspace crates that aren't published, or are only
# published to private registries.
# To see how to mark a crate as unpublished (to the official registry),
# visit https://doc.rust-lang.org/cargo/reference/manifest.html#the-publish-field.
ignore = false
# One or more private registries that you might publish crates to, if a crate
# is only published to private registries, and ignore is true, the crate will
# not have its license(s) checked
registries = [
    #"https://sekretz.com/registry
]

# This section is considered when running `cargo deny check bans`.
# More documentation about the 'bans' section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html
[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Lint level for when a crate version requirement is `*`
wildcards = "allow"
# The graph highlighting used when creating dotgraphs for crates
# with multiple versions
# * lowest-version - The path to the lowest versioned duplicate is highlighted
# * simplest-path - The path to the version with the fewest edges is highlighted
# * all - Both lowest-version and simplest-path are used
highlight = "all"
# List of crates that are allowed. Use with care!
allow = [
    #{ name = "ansi_term", version = "=0.11.0" },
]
# List of crates to deny
deny = [
    # Each entry the name of a crate and a version range. If version is
    # not specified, all versions will be matched.
    #{ name = "ansi_term", version = "=0.11.0" },
    #
    # Wrapper crates can optionally be specified to allow the crate when it
    # is a direct dependency of the otherwise banned crate
    #{ name = "ansi_term", version = "=0.11.0", wrappers = [] },
]
# Certain crates/versions that will be skipped when doing duplicate detection.
skip = [
    #{ name = "ansi_term", version = "=0.11.0" },
]
# Similarly to `skip` allows you to skip certain crates during duplicate
# detection. Unlike skip, it also includes the entire tree of transitive
# dependencies starting at the specified crate, up to a certain depth, which is
# by default infinite
skip-tree = [
    #{ name = "ansi_term", version = "=0.11.0", depth = 20 },
]

# This section is considered when running `cargo deny check sources`.
# More documentation about the 'sources' section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/sources/cfg.html
[sources]
# Lint level for what to happen when a crate from a crate registry that is not
# in the allow list is encountered
unknown-registry = "warn"
# Lint level for what to happen when a crate from a git repository that is not
# in the allow list is encountered
unknown-git = "warn"
# List of URLs for allowed crate registries. Defaults to the crates.io index
# if not specified. If it is specified but empty, no registries are allowed.
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# List of URLs for allowed Git repositories
allow-git = []

[sources.allow-org]
# 1 or more github.com organizations to allow git sources for
github = [""]
# 1 or more gitlab.com organizations to allow git sources for
gitlab = [""]
# 1 or more bitbucket.org organizations to allow git sources for
bitbucket = [""]

```
