### ISSUE TITLE
Regression in license clarification?

### ISSUE THREAD

**Issue by djc** [EmbarkStudios/cargo-deny#452]
**Describe the bug**

Given the following config:

```toml
[licenses]
allow = [
    "Apache-2.0",
    "ISC",
    "LicenseRef-ring",
    "LicenseRef-webpki",
    "MIT",
    "Unicode-DFS-2016",
]
confidence-threshold = 1.0

[[licenses.clarify]]
name = "ring"
expression = "LicenseRef-ring"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

# XXX: Figure out how to deal with the Google-source test data
# https://github.com/briansmith/webpki/issues/148.
[[licenses.clarify]]
name = "webpki"
expression = "LicenseRef-webpki"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]
```

I get the following error:

```
error[L003]: rustls-webpki = 0.22.0-alpha.1 is unlicensed
  ┌─ rustls-webpki 0.22.0-alpha.1 (path+file:///Users/djc/src/webpki):2:9
  │
2 │ name = "rustls-webpki"
  │         ^^^^^^^^^^^^^ a valid license expression could not be retrieved for the crate
3 │ version = "0.22.0-alpha.1"
4 │ license = ""
  │            - license expression was not specified
5 │ license-files = [
6 │     { path = "LICENSE", hash = 0x001c7e6c, score = 0.85, license = "ISC" },
  │                                                    ---- low confidence in the license text
  │
  = rustls-webpki v0.22.0-alpha.1

warning[L006]: license was not encountered
   ┌─ /Users/djc/src/webpki/deny.toml:11:5
   │
11 │     "LicenseRef-webpki",
   │     ^^^^^^^^^^^^^^^^^^^ unmatched license allowance
```

It's not reporting a different license hash (and the license and hash haven't changed in the two years since this config was setup). So what is this trying to tell me exactly?
