### ISSUE TITLE
Ability to deny all warnings

### ISSUE THREAD

**Issue by Nemo157** [EmbarkStudios/cargo-deny#454]
**Is your feature request related to a problem? Please describe.**
I want to easily deny all the things that `cargo-deny` considers as a warning by default in my CI jobs.

**Describe the solution you'd like**
Something similar to `cargo check --deny=warnings`. Because there's not a general purpose `--deny` flag this could maybe just be `cargo deny check --deny-warnings`.

**Describe alternatives you've considered**
Copy-pasting a base `deny.toml` into all my crates, or somehow merging it into any local config from a CI job

```toml
[advisories]
unmaintained = "deny"
yanked = "deny"
[licenses]
copyleft = "deny"
[bans]
multiple-versions = "deny"
wildcards = "deny"
[sources]
unknown-registry = "deny"
unknown-git = "deny"
```
