### ISSUE TITLE
Wildcard version warnings generated git dependencies with fixed commit

### ISSUE THREAD

**Issue by TimJentzsch** [EmbarkStudios/cargo-deny#488]
**Describe the bug**

When specifying a git dependency with a `rev` (i.e., fixed commit hash) entry, the version wildcard warning is triggered.
However, because of the commit hash, an exact version has been specified.

**To Reproduce**
1. Add a git dependency with a commit specified, e.g.:

    ```toml
    [dependencies]
    bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap", rev = "2967a394dc59c29fac14cb8cb187d601ea604a1e" }
    ```
3. Ban wildcard dependencies in `deny.toml`:

    ```toml
    [bans]
    wildcards = "deny"
    ```

4. Run `cargo deny check`. A wildcard error is triggered for the git dependency.
    In our case, it looks like this (with two git dependencies):

    ```
    error[wildcard]: found 3 wildcard dependencies for crate 'emergence_lib'
      ┌─ /home/tim/Documents/bevyengine/Emergence/emergence_lib/Cargo.toml:2:1
      │
    2 │ bevy-trait-query = '*'
      │ ^^^^^^^^^^^^^^^^^^^^^^ wildcard crate entry
    3 │ bevy_ecs_tilemap = '*'
    4 │ bevy_ecs_tilemap = '*'
      │ ^^^^^^^^^^^^^^^^^^^^^^
      │ │
      │ wildcard crate entry
      │ wildcard crate entry
      │
      = emergence_lib v0.1.0
        └── emergence_game v0.1.0

**Expected behavior**

The wildcard warning is only triggered for git dependencies if the commit hash is not fixed, i.e. when the `rev` attribute is missing.

**Device:**
 - OS: Linux (Pop!_OS)
 - Version `0.13.5`
