### ISSUE TITLE
licenses.exceptions.version = "*" does not work

### ISSUE THREAD

**Issue by jayvdb** [EmbarkStudios/cargo-deny#496]
**Describe the bug**
The version in a `licenses.exceptions` entry can not be `*`, but I think that `*` is allowed for `bans.skip.version`.

That appears to be counter-intuitive, as a `licenses.exceptions` entry is already very precise because it requires a key `allow` which indicates the licenses to be allowed for that crate, and the version of the crate is less interesting.  If a new version changes the license that isnt in the `allow`, the new crate version will trigger the license exception to be ignored, and depending on config this will cause `cargo-deny` to error.

**To Reproduce**
We are using the following to allow any version of wiremock, because it is only a test dependency
```toml
[[bans.skip]]
name = "wiremock"
version = "*"
```

However this does not work
```toml
[[licenses.exceptions]]
allow = ["MPL-2.0"]
name = "progenitor"
version = "*"
```
Explicit version does work
```toml
[[licenses.exceptions]]
allow = ["MPL-2.0"]
name = "progenitor"
version = "0.2.1-dev"
```

**Expected behavior**
`licenses.exceptions.version = "*"` should allow any version of the crate, subject to the `licenses.exceptions.allow` matching the license of the crate.
