### ISSUE TITLE
Private sparse registry false positive

### ISSUE THREAD

**Issue by Sculas** [EmbarkStudios/cargo-deny#507]
**Describe the bug**
I have a private Cargo sparse registry. I've added the registry in `.cargo/config.toml`, and then used it in my `Cargo.toml` file like this:
```toml
# .cargo/config.toml
[registries]
example-internal = { index = "sparse+https://example.com/example/crates/" }

# Cargo.toml
[dependencies]
mylib = { version = "1", registry = "example-internal" }
# ...
```
I have my sources setup like this:
```toml
[sources]
unknown-registry = "deny"
allow-registry = [
    "https://github.com/rust-lang/crates.io-index",
    "sparse+https://example.com/example/crates/",
]
```
However, when running `cargo deny check`, I get these errors:
```console
error[source-not-allowed]: detected 'registry' source not explicitly allowed
    ┌─ example\Cargo.lock:257:9
    │
257 │ mylib 1.0.0 sparse+https://example.com/example/crates/
    │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ source
    │
    = mylib v1.0.0
      └── (dev) example v0.1.0

warning[unmatched-source]: allowed source was not encountered
   ┌─ example\deny.toml:23:5
   │
23 │     "sparse+https://example.com/example/crates/",
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no crate source matched these criteria

advisories ok, bans ok, licenses ok, sources FAILED
```

**To Reproduce**
The information provided above should be enough, but you'll need to find a sparse registry to reproduce it.

**Expected behavior**
It should pass without any problems because the sources have been set up correctly.

**Device:**
 - OS: Windows 11 22H2
 - Version: d37423a2da2c588d99120c190fc1b8f51a9ff666
