### ISSUE TITLE
crates-io mirror support

### ISSUE THREAD

**Issue by royb3** [EmbarkStudios/cargo-deny#515]
We have a mirror for crates-io, which we have configured in our `.cargo/config` like this:
```toml
[source.mirror]
registry = "http://crates-mirror"

[source.crates-io]
replace-with = "mirror"
```

The cargo.lock still references crates-io, for example:
```toml
[[package]]
name = "serde_json"
version = "1.0.96"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "057d394a50403bcac12672b2b18fb387ab6d289d957dab67dd201875391e52f1"
dependencies = [
 "itoa",
 "ryu",
 "serde",
]
```

I would expect that cargo deny could figure out that crates-io was replaced with a mirror and use the mirror registry instead. But on an air gapped network, it still tries to fetch the crates from crates-io.

It does this to resolve if a yanked version of a crate is used, all other functions seem to work as expected.

Would it be possible to add support mirrors as configured in the local .cargo/config files?
