### ISSUE TITLE
Is there a way to allow licenses for specific packages?

### ISSUE THREAD

**Issue by iliana** [EmbarkStudios/cargo-deny#53]
For some licenses we prefer to restrict allowing them to specific packages. In cargo-deny v0.2 we did this with skip, along the lines of:

```toml
[[licenses.skip]]
name = "copyless"
licenses = ["MPL-2.0"]
```

I can't seem to find a way to do this in v0.4; clarifications seem to be for changing what the detected license is.

(I accidentally hit enter while typing the issue title, sorry for the initial content that was just the issue template)
