### ISSUE TITLE
Handle GNU shenanigans correctly

### ISSUE THREAD

**Issue by pikajude** [EmbarkStudios/cargo-deny#55]
Here's my deny.toml:
``` toml
[licenses]
deny = ["GPL-1.0-or-later"]
```

and Cargo.toml:
``` toml
[package]
name = "cargo-deny-test"
version = "0.1.0"
edition = "2018"
license = "GPL-1.0"
```

I would expect `cargo deny` to reject this crate. However:

```
warning: license requirements satisfied

   ┌── cargo-deny-test 0.1.0 (path+file:///Users/judetaylor/.code/cargo-deny-test):4:12 ───
   │
 4 │ license = "GPL-1.0"
   │            ^^^^^^^ license expression retrieved via Cargo.toml `license`
   ·
 4 │ license = "GPL-1.0"
   │            ------- accepted: license is considered copyleft
   │
   = cargo-deny-test v0.1.0
```

Is this intended? Are these two GPL licenses actually considered distinct?
