### ISSUE TITLE
Error: failed to open advisory database

### ISSUE THREAD

**Issue by sunpan822** [EmbarkStudios/cargo-deny#692]
### Describe the bug
cargo deny check.........................................................Failed
- hook id: cargo-deny
- exit code: 1

[ERROR] failed to open advisory database: "/home/user/.cargo/advisory-db/github.com-2f857891b7f43c59" does not appear to be a git repository: Could not retrieve metadata of "/home/user/.cargo/advisory-db/github.com-2f857891b7f43c59": No such file or directory (os error 2)

### To reproduce

1.Install pre-commit:
```shell
pip install pre-commit
```

2.Install the latest version of cargo-deny:
```shell
cargo install --locked cargo-deny
```

3. Install other crate tools:
```shell
cargo install typos-cli
cargo install git-cliff
cargo install cargo-nextest --locked
```

3.Write a pre-commit file
```yaml
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format files with rustfmt.
        entry: bash -c 'cargo fmt -- --check'
        language: rust
        files: \.rs$
        args: []
      - id: cargo-deny
        name: cargo deny check
        description: Check cargo dependencies
        entry: bash -c 'cargo deny check -d'
        language: rust
        files: \.rs$
        args: []
      - id: typos
        name: typos
        description: check typo
        entry: bash -c 'typos'
        language: rust
        files: \.*$
        pass_filenames: false
      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: bash -c 'cargo check --all'
        language: rust
        files: \.rs$
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        description: Lint rust sources
        entry: bash -c 'cargo clippy --all-targets --all-features --tests --benches -- -D warnings'
        language: rust
        files: \.rs$
        pass_filenames: false
      - id: cargo-test
        name: cargo test
        description: unit test for the project
        entry: bash -c 'cargo nextest run --all-features'
        language: rust
        files: \.rs$
        pass_filenames: false
```

Run:
```shell
git commit -m "Add an encryption feature."
```

### cargo-deny version

cargo-deny 0.16.1

### What OS were you running cargo-deny on?

Linux
