### ISSUE TITLE
Bug: false-positive warning "scheme modifiers are unnecessary"

### ISSUE THREAD

**Issue by MOZGIII** [EmbarkStudios/cargo-deny#706]
### Describe the bug

I get the `scheme modifiers are unnecessary` warning for `git+ssh://` URL at `allow-git`.

### To reproduce

```toml
[sources]
allow-git = ["git+ssh://git@github.com/my/repo.git"]
```

### cargo-deny version

cargo-deny 0.16.1

### What OS were you running cargo-deny on?

MacOS
