### ISSUE TITLE
Bug: Docs say `[build]`, `[build.bypass]` etc, actual syntax is `[bans.build]`, `[[bans.build.bypass]]`

### ISSUE THREAD

**Issue by tv42** [EmbarkStudios/cargo-deny#764]
### Describe the bug

It looks like https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html forgot the "top-level" of the TOML structure, making the examples listed there not copy-pastable.

### To reproduce

```toml
[build]
script-extensions = ["cs"]

[[build.bypass]]
crate = "crate-name"
allow-globs = [
    "scripts/*.cs",
]
```

```console
$ cargo deny check
error[unexpected-keys]: found 1 unexpected keys, expected: ["advisories", "bans", "licenses", "sources", "graph", "targets", "exclude", "features", "all-features", "no-default-features", "exclude-dev", "output", "feature-depth"]
  ┌─ /blah/deny.toml:1:2
  │
1 │ [build]
  │  ─────

2025-05-13 20:02:55 [ERROR] failed to deserialize config from '/blah/deny.toml'
```

### cargo-deny version

cargo-deny 0.18.2

### What OS were you running cargo-deny on?

Linux

**Comment by lafrenierejm** [comment]
This appears to have been fixed. The configuration from <https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html> as I retrieved it just now correctly includes the `bans` parent attribute:

```toml
[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true
highlight = "simplest-path"
workspace-default-features = "warn"
external-default-features = "deny"
allow = [
    { name = "all-versionsa" },
    "version-rangea:<0.1.1",
    "specific-versionb@0.1.2",
    "any-version",
]
deny = [
    "specific-versiond@0.1.9",
    { name = "all-versionsd", wrappers = [
        "specific-versiona",
    ], reason = "we want to get rid of this crate but there is still one user of it" },
]
skip-tree = [{ name = "blah", depth = 20 }]

[bans.workspace-dependencies]
duplicates = "allow"
include-path-dependencies = false
unused = "allow"

[[bans.skip]]
name = "rand"
version = "=0.6.5"

[[bans.features]]
name = "featured-krate"
version = "1.0"
deny = ["bad-feature"]
allow = ["good-feature"]
exact = true
reason = "`bad-feature` is bad"

[bans.build]
allow-build-scripts = [{ name = "all-versionsa" }]
executables = "warn"
interpreted = "deny"
script-extensions = ["cs"]
enable-builtin-globs = true
include-dependencies = true
include-workspace = true
include-archives = true

[[bans.build.bypass]]
name = "allversionsa"
build-script = "5392f0e58ad06e089462d93304dfe82337acbbefb87a0749a7dc2ed32af04af7"
required-features = ["feature-used-at-build-time"]
allow-globs = ["scripts/*.cs"]
allow = [
    { path = "bin/x86_64-linux", checksum = "5392f0e58ad06e089462d93304dfe82337acbbefb87a0749a7dc2ed32af04af7" },
]
```
