### ISSUE TITLE
Bug: unused workspace dependency false positive when `[graph] exclude` is used

### ISSUE THREAD

**Issue by eric-seppanen** [EmbarkStudios/cargo-deny#772]
### Describe the bug

I exclude a few crates from cargo-deny analysis, to selectively allow crates with problematic dependencies in non-production tools.

However, when I enable unused-workspace-dependencies detection, I find that each excluded crate is incorrectly reported as an unused workspace dependency.

### To reproduce

I created a minimal workspace:
```toml
[workspace]
resolver = "3"
members = ["test1"]

[workspace.dependencies]
anyhow = "1.0.98"
```

```toml
[package]
name = "test1"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
```

I then created a default `deny.toml` with `cargo deny init` and made two additions:
```toml
[graph]
exclude = [
  "anyhow"
]
```
```toml
[bans.workspace-dependencies]
unused = "deny"
```

Now, `cargo deny check bans` reports:
```plaintext
error[unused-workspace-dependency]: workspace dependency is declared, but unused
  ┌─ .../Cargo.toml:6:1
  │
6 │ anyhow = "1.0.98"
  │ ━━━━━━ unused workspace dependency

bans FAILED
```

### cargo-deny version

cargo-deny 0.18.2

### What OS were you running cargo-deny on?

Linux
